### ISSUE TITLE
Release for latest version

### ISSUE THREAD

**Issue by jjc2718** [dirmeier/netReg#38]
Any plans for a release of the latest version of the code? Currently, following the installation instructions at https://dirmeier.github.io/netReg/ gives a pretty outdated install that doesn't match a lot of the documentation (e.g. newer link functions don't exist, code hasn't been ported to TensorFlow). Would be good to update the version on Bioconductor as well as the tarball.

FWIW, I installed the latest version using `devtools::install_github` and it seems to work (although I know you recommend against this) - let me know if there's a better way to get the latest code.

**Comment by dirmeier** [comment]
Hey, thanks for your message. Glad if ppl use the package.

Yeah, you are right. Problem currently is that Bioconductor doesn't support TensorFlow yet on their servers, so I thought I don't move the docu and everything  to TF. That being said, I was thinking of removing it from Bioc anyways and put it on CRAN, such that development is easier and we are not bound to Bioc infrastructure anymore.  

I am kinda on a tight schedule these days (papers/defense/etc.). Once this is over, I'll migrate everything to TF, update the docu, and fix bugs that might exist. I can, however, only do that earliest next week or the week after that.

Cheers,
Simon
