### ISSUE TITLE
should cv.edgenet without G.x or G.y perform the same as glmnet

### ISSUE THREAD

**Issue by kengcher** [dirmeier/netReg#40]
Hi

Should cv.edgenet without any input G.x or G.y perform the same as glmnet (family='gaussian')? I had much worse rmse values using cv.edgenet (86.3) vs glmnet (20.6)?

Thank you.

**Comment by dirmeier** [comment]
Hi,

no unfortunately they wont be the same. `edgenet` is built on [Fu's lassoshooting](https://www.tandfonline.com/doi/abs/10.1080/10618600.1998.10474784), or more recently based on TensorFlow and optimized with Adam. Afaik, `glmnet` doesn't merely optimize the target (which is the Elastic net penalty, not the Lasso penalty as in `edgenet`), but also does, among other things, internally standardize data, etc. I haven't found out the exact preprocessing steps that `glmnet` does, such that the estimated coefficients would be the same. 

Would be happy to learn more on this, in case you know.

Cheers,
Simon
