### ISSUE TITLE
error: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by vishalbelsare** [dirmeier/netReg#46]
Trying to install from the Git repo, I am faced with the following : 

RcppExports.cpp: In function ‘SEXPREC* _netReg_node_degrees_(SEXP)’:
RcppExports.cpp:41:17: error: format not a string literal and no format arguments [-Werror=format-security]
   41 |         Rf_error(CHAR(rcpp_msgSEXP_gen));
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
RcppExports.cpp: In function ‘SEXPREC* _netReg_laplacian_(SEXP)’:
RcppExports.cpp:75:17: error: format not a string literal and no format arguments [-Werror=format-security]
   75 |         Rf_error(CHAR(rcpp_msgSEXP_gen));
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
RcppExports.cpp: In function ‘SEXPREC* _netReg_intercept_(SEXP, SEXP, SEXP)’:
RcppExports.cpp:111:17: error: format not a string literal and no format arguments [-Werror=format-security]
  111 |         Rf_error(CHAR(rcpp_msgSEXP_gen));
      |         ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make: *** [/usr/lib64/R/etc/Makeconf:204: RcppExports.o] Error 1
ERROR: compilation failed for package ‘netReg’

**Comment by dirmeier** [comment]
Hi, I haven't maintained this package in four years, since I don't use R anymore (but I should've changed the badge to inactive or whatever). Ill deprecate it properly asap. I think you can fork the package and update the outdated parts easily though.

Cheers, 
Simon
